//
//  DayNightStyleKit.swift
//  DayNightStyleKit
//
//  Created by WendyAbrantes on 06/10/2015.
//  Copyright (c) 2015 Wenders Digital LTD. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class DayNightStyleKit : NSObject {

    //// Cache
    private struct Cache {
        static let gray1: UIColor = UIColor(red: 0.878, green: 0.918, blue: 0.776, alpha: 1.000)
        static let gray2: UIColor = UIColor(red: 0.827, green: 0.827, blue: 0.827, alpha: 1.000)
        static let gray3: UIColor = UIColor(red: 0.231, green: 0.255, blue: 0.271, alpha: 1.000)
        static let gray4: UIColor = UIColor(red: 0.110, green: 0.110, blue: 0.110, alpha: 1.000)
        static let yellow1: UIColor = UIColor(red: 1.000, green: 0.890, blue: 0.384, alpha: 1.000)
        static let yellow2: UIColor = UIColor(red: 0.894, green: 0.780, blue: 0.224, alpha: 1.000)
        static let blue1: UIColor = UIColor(red: 0.541, green: 0.898, blue: 0.996, alpha: 1.000)
        static let blue2: UIColor = UIColor(red: 0.431, green: 0.773, blue: 0.855, alpha: 1.000)
        static let white: UIColor = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)
    }

    //// Colors

    public class var gray1: UIColor { return Cache.gray1 }
    public class var gray2: UIColor { return Cache.gray2 }
    public class var gray3: UIColor { return Cache.gray3 }
    public class var gray4: UIColor { return Cache.gray4 }
    public class var yellow1: UIColor { return Cache.yellow1 }
    public class var yellow2: UIColor { return Cache.yellow2 }
    public class var blue1: UIColor { return Cache.blue1 }
    public class var blue2: UIColor { return Cache.blue2 }
    public class var white: UIColor { return Cache.white }

    //// Drawing Methods
}
